name: Fetch Data

on:
  push:
    branches:
      - main  # Trigger the workflow on any push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  fetch-data:
    runs-on: ubuntu-latest  # Or your desired runner OS
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3  # Checks out your code

      - name: Install jq (optional for processing JSON data)
        run: |
          sudo apt update
          sudo apt install jq  # Tool for processing JSON data (optional)

      - name: Fetch data from Google Sheet
        run: |
          curl -X GET \
          https://sheets.googleapis.com/v4/spreadsheets/19r8IWr7xwpP2NhtQzs_5m00FaKbGcOfN95uiyr55zH4/values/A:A \
          -H 'Authorization: ya29.a0Ad52N38GmCvS4ixOToJ5GiQNkW7zDLCKxpL5GojTjcWWaPIaLcR6AA-l0B73eaf7hPmEGkOTOQZXxlcL310NzUAuJAoRRSlU9EfPOkEgtRQGk9cOQokcZ3ee2GfKfS10_c_dzbKYXIS7J0SJpTDccshw54Lbr5mwPSC2aCgYKAfsSARESFQHGX2MiyPDXpoyqLW7WkaJmwdIPoQ0171' \
          -H 'Content-Type: application/json' \
          -o data.json

      - name: Process data (optional)
        run: |  # Example: Extract specific data using jq (optional)
          DATA=$(echo ${{ steps.fetch-data.outputs.body }} | jq '.[0]')  # Assuming first element
          echo "Extracted data: $DATA"

      - name: Update app-ads.txt
        run: |  # Update your app-ads.txt file with fetched data
          echo "$DATA" >> app-ads.txt  # Append data to app-ads.txt (adjust based on your needs)

      - name: Add and commit changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add app-ads.txt
          git commit -m "Update app-ads.txt with fetched data (automated)"
          git push origin main  # Push changes to main branch (adjust branch name if needed)