name: Fetch Data

on:
  push:
    branches:
      - main  # Trigger the workflow on any push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  fetch-data:
    runs-on: ubuntu-latest  # Or your desired runner OS
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out your code

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install jq 

      - name: Fetch data from Google Sheet
        run: |
          curl --request GET \
          --url 'https://sheets.googleapis.com/v4/spreadsheets/19r8IWr7xwpP2NhtQzs_5m00FaKbGcOfN95uiyr55zH4/values/A:A' \
          --header 'Authorization: Bearer ya29.a0Ad52N3-phzPKiUlDp82zPRhYghxWZnRqPn6MJIeHGMpOEOjvt1hYEWPn3OQxphpmzh0Kh_QFln81EE40ZfUXvgFnG3Ce5212QODmSmP9Oe9FsNt6lzKVHk6GrFKeA8toeGBwtho9O2ePRUMzWrCXTG6Q0Ucdka5CkElKaCgYKARASARESFQHGX2MivhnK3jNFweTyBHqRS4TgkA0171' \
          --header 'Accept: application/json' \
          --output data.json

      - name: Print fetched data
        run: |
          cat data.json

      - name: Extract values array
        run: |
          jq -r '.values[] | .[]' data.json > values.txt
          
      - name: Update app-ads.txt
        run: |
          sed -i 's/,$//' values.txt  # Remove trailing comma
          sed -i 's/^ *//' values.txt  # Remove leading whitespace
          cp values.txt app-ads.txt

      - name: Create virtual environment
        run: |
          python3 -m venv venv

      - name: Activate virtual environment
        run: |
          source venv/bin/activate

      - name: Install Python dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run reformat.py
        run: |
          python3 reformat.py
      
      - name: Print app-ads.txt
        run: |
          cat app-ads.txt


  deploy:
    runs-on: ubuntu-latest
    needs: fetch-data
    strategy:
      matrix:
        repositories:
          - { url: "zsocial", distribution: E365KI34AV697H, src: "./app-ads.txt", role_arn: "arn:aws:iam::060454969817:role/zsocial-github-action" }
    steps:
      - name: Assume role
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2.2.0
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ matrix.repositories.role_arn }}
          role-duration-seconds: 900
      - name: Upload file to S3 bucket
        run: |
          aws s3 cp ./app-ads.txt s3://${{ matrix.repositories.url }} --region ap-south-1
      - name: Invalidate cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ matrix.repositories.distribution }} --paths "/app-ads.txt"
