name: Fetch Data

on:
  push:
    branches:
      - main  # Trigger the workflow on any push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  fetch-data:
    runs-on: ubuntu-latest  # Or your desired runner OS
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out your code

      - name: Install jq (optional for processing JSON data)
        run: |
          sudo apt update
          sudo apt install jq  # Tool for processing JSON data (optional)

      - name: Fetch data from Google Sheet
        run: |
          curl --request GET \
          --url 'https://sheets.googleapis.com/v4/spreadsheets/19r8IWr7xwpP2NhtQzs_5m00FaKbGcOfN95uiyr55zH4/values/A:A' \
          --header 'Authorization: Bearer ya29.a0Ad52N3_mqwCKtjd1WNcy1-zPU5AiDC6UP7kQrS5ZpUg-Z8OQmHAgivSkyKdyRJfFLKL6d3OF6YzCzzDdX1N-L5kH4T8kV1s_zigzK_1XYMJPFV4YUt3Xs6A8UpD1ZLZjDSjDIz6L9rpRv16VuFA5sKK-fjpEQFKUoRpiaCgYKAZsSARESFQHGX2Mior06aQDCY6R2xqrtHIZTyg0171' \
          --header 'Accept: application/json' \
          --output data.json

      - name: Print fetched data
        run: |
          cat data.json

      - name: Process data
        run: |
          jq '.values[]' data.json > app-ads.txt

      - name: Print app-ads.txt data
        run: |
          cat app-ads.txt

        