name: Fetch Data

on:
  push:
    branches:
      - main  # Trigger the workflow on any push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch data from Google Sheets
        run: |
          # Make an HTTP request to the URL of your Google Apps Script web app
          # Store the response data in a file (e.g., data.json)
          curl -L 1JhGOIjekq0icQwwnf-Lj2Nu-bfW6A2JeLogxQpb3xIw > data.json

      - name: Update app-ads.txt
        run: |
          # Parse the data from data.json and update app-ads.txt
          # Example: python update_app_ads.py data.json

      - name: Configure Git
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add app-ads.txt
          git commit -m "Update app-ads.txt"
          git push origin main
